spring:
  datasource:
    url: jdbc:mysql:replication://localhost:13306,localhost:13306/develop
    username: dev-user
    password: dev-pass
    driverClassName: com.mysql.jdbc.Driver

  redis:
    host: localhost
    port: 16379

logging:
  level:
    org.springframework: INFO

