version: '3'

services:
  redis:
    image: "redis:5.0"
    ports:
      - "16379:6379"
    volumes:
      - "./redis/data:/data"

  mysql:
    build: ./mysql/  # Dockerfileを利用
    ports:
      - "13306:3306" # ポートを開ける
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=dev-user
      - MYSQL_PASSWORD=dev-pass
      - MYSQL_DATABASE=develop
    volumes:
      - "./mysql/data:/var/lib/mysql"