version: '3'

services:
  redis:
    image: "redis:5.0"
    ports:
      - "16379:6379"
    volumes:
      - "./data/redis:/data"

  mysql-master:
    build: mysql-master/  # Dockerfileを利用
    ports:
      - "13306:3306" # ポートを開ける
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=dev-user
      - MYSQL_PASSWORD=dev-pass
      - MYSQL_DATABASE=develop

  mysql-slave:
    build: mysql-slave/  # Dockerfileを利用
    ports:
      - "13307:3306" # ポートを開ける
    depends_on:
      - mysql-master # マスターDBに依存
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=dev-user
      - MYSQL_PASSWORD=dev-pass
      - MYSQL_DATABASE=develop